#!/usr/bin/env bash
export controller_ip_address=10.209.24.147
export floating_allocation_pool_start=10.209.26.20
export floating_allocation_pool_end=10.209.29
export vlan_pool_start=71
export vlan_pool_end=80

