#!/usr/bin/env bash

public_interface=$(sudo ip link show | grep -e "^3:" | awk '{print $2}' | cut -d':' -f1)
export public_interface
echo $public_interface


export controller_ip_address=10.209.24.134
export public_gateway=10.209.86.1
export floating_range=10.209.86.0/24
export public_interface_ip=10.209.86.25
export floating_allocation_pool_start=10.209.86.26
export floating_allocation_pool_end=10.209.86.35
export vlan_pool_start=51
export vlan_pool_end=60
